config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get    '/admin',   to: 'sessions#new'
  post   '/admin',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :events do
    get :ics, on: :member
    post :subscribe, on: :member
    get :filter, on: :collection
  end
  resources :organizers
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase }
  validates :email, presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

end

# Returns the hash digest of the given string.
def AdminUser.password(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                              BCrypt::Engine.cost
  BCrypt::Password.create(string, cost: cost)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  require 'icalendar'

  belongs_to :organizer
  has_attached_file :event_image, styles: { medium: '300x300#', thumb: '100x100#' },
                                  storage: :s3, 
                                  bucket: 'test-event-app-rails', 
                                  s3_protocol: 'https'
  
  validates_attachment_content_type :event_image, content_type: /\Aimage\/.*\z/, presence: true
  validates_presence_of :name

  scope :city_filter, ->(city) { where city: city if city.present? }
  scope :month_filter, ->(month) { where('extract(month  from date) = ?', month) if month.present? }
  scope :organizer_filter, ->(organizer_id) { where organizer_id: organizer_id if organizer_id.present? }
  scope :past_or_upcoming_filter, ->(par) { where("date #{par} ?", DateTime.now) if par.present? }

  def self.filter(filter_params)
    Event.city_filter(filter_params[:city])
         .month_filter(filter_params[:month])
         .organizer_filter(filter_params[:organizer_id])
         .past_or_upcoming_filter(filter_params[:par])
         .order('date DESC')
  end

  def ics_create
    filename = "#{name}.ics"
    # Create a calendar with an event (standard method)
    cal = Icalendar::Calendar.new
    cal.event do |e|
      e.dtstart     = date
      e.dtend       = date
      e.summary     = name
      e.description = description
      e.location    = "#{city}, #{address}"
    end
  end

end

app/models/organizer.rb
class Organizer < ApplicationRecord
  has_many :events
  validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :admin_is_logged_in, only: [:new, :edit, :update, :destroy]
  include EventsHelper
  include SessionsHelper

  private
  
  # Confirms that admin is logged in.
  def admin_is_logged_in
    unless logged_in?
      flash[:danger] = 'Доступ закрыт'
      redirect_to root_url
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.paginate(page: params[:page], per_page: 18).order('date DESC')
  end

  def show
    @event = Event.includes(:organizer).find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = 'Мероприятие успешно создано!'
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = 'Мероприятие изменено'
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:success] = 'Мероприятие удалено'
      redirect_to events_url
    else
      render 'index'
    end
  end

  def ics
    @event = Event.find(params[:id])
    send_data @event.ics_create.to_ical, type: 'text/calendar', disposition: 'attachment',
      filename: "#{@event.name}.ics"
  end

  def subscribe
    flash[:success] = "Успешно подписаны на напоминания! #{params[:email]}"
    SendEmailWorker.perform_async(params[:email], params[:id])
  end

  # For filters use scopes, defined in event.rb
  def filter
    @events = Event.filter(filter_params).paginate(page: params[:page], per_page: 18)
    if @events.blank?
      flash.now[:warning] = 'Извините, ничего не найдено по вашему запросу :('
    end
    render 'index'
  end

  private

  def event_params
    params.require(:event).permit(:name, :city, :address,
                                  :date, :organizer_id, :description, :link, :event_image)
  end

  def filter_params
    params.permit(:city, :month, :organizer_id, :par)
  end

  
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController

  def index
    @organizers = Organizer.paginate(page: params[:page], per_page: 18)
  end

  def show
    @organizer = Organizer.includes(:events).where(id: params[:id]).find(params[:id])
  end

  def new
    @organizer = Organizer.new
    @events = @organizer.events
  end

  def create
    @organizer = Organizer.new(organizer_params)
    if @organizer.save
      flash[:success] = 'Организатор успешно создан!'
      redirect_to @organizer
    else
      render 'new'
    end
  end

  def edit
    @organizer = Organizer.find(params[:id])
  end

  def update
    @organizer = Organizer.find(params[:id])
    if @organizer.update(organizer_params)
      flash[:success] = 'Организатор успешно изменен'
      redirect_to @organizer
    else
      render 'edit'
    end
  end

  def destroy
    @organizer = Organizer.find(params[:id])
    if @organizer.destroy
      flash[:success] = 'Организатор удален'
      redirect_to organizers_url
    else
      render 'edit'
    end
  end

  private

  def organizer_params
    params.require(:organizer).permit(:name, :description, :events)
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
  end
  
  def create
    user = AdminUser.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = 'Hello, admin!'
      redirect_to root_path
    else
      flash.now[:danger] = 'Неправильный email/пароль'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'IT Мероприятия'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
     end
  end

  def error_msg(controller)
    controller.controller_name == 'events' ? @event : @organizer
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged in user (if any)
  def current_user
    @current_user ||= AdminUser.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/events/_event.html.erb
<div class="col-md-6">
    <div class="card h-100">
        <div class="row no-gutters">
            <div class="col-auto px-2">
                <%= image_tag event.event_image.url(:thumb), class: "card-img-left" %>
            </div>
            <div class="col">
                <h5 class="card-title"><%= link_to event.name, event %></h5>
                <p class="card-text">
                    <%= l(event.date, format: '%d %B %Y, %-H:%M') %><br>
                    <p><%= event.city %>, <%= event.address %></p>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/events/_form.html.erb
<div class="row">
  <div class="event-form col-md-6 col-md-offset-3">
    <%= form_for @event, html: { multipart: true } do |f| %>
      <%= render 'shared/error_messages', object: @event %>

      <%= f.label 'Название' %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label 'Город' %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label 'Адрес' %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label 'Дата и время' %>
      <%= f.datetime_select :date, class: 'form-control' %>

      <%= f.label 'Организатор' %>
      <span class="row">
        <%= f.collection_select :organizer_id, Organizer.all, :id, :name, class: 'form-control' %>
        <%= link_to '/organizers/new', title: 'Добавить нового организатора' do %>
              <%= material_icon.people.md_36 %>
        <% end %>
      </span>

      <%= f.label 'Описание' %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label 'Ссылка' %>
      <%= f.text_field :link, class: 'form-control' %>

      <%= f.label 'Изображение' %>
      <%= f.file_field :event_image %>
      
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<% provide(:title, 'Изменить мероприятие ') %>
<% provide(:button_text, 'Сохранить изменения') %>
<h1>Update event</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<% provide(:title, '') %>
<div class="row navbar-admin">
  <h1>Все мероприятия</h1>
  <% if logged_in? %>
    <span class="ml-auto">
      <%= link_to '/events/new', title: 'Добавить мероприятие' do %>
        <%= material_icon.add.md_36 %>
      <% end %>
    </span>
  <% end %>  
</div>
<div class="container-fluid events-container">
  <div class="row event-cards">
    <% @events.each do |event| %>
      <%= render event %>
    <% end %>
  </div>
</div>
<%= will_paginate @events, list_classes: %w(pagination justify-content-center) %>

app/views/events/new.html.erb
<% provide(:title, 'Новое мероприятие') %>
<% provide(:button_text, 'Создать новое мероприятие') %>
<h1>New event</h1>
<%= render 'form' %>
  

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<div class="row">
<h1><%= @event.name %></h1>
<% if logged_in? %>
    <ul class="navbar-nav navbar-admin ml-auto">
      <li class="nav-item">
        <%= link_to edit_event_path, title: 'Изменить мероприятие' do %>
          <%= material_icon.mode_edit.md_36 %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to @event, method: :delete, title: 'Удалить мероприятие', data: { confirm: 'Вы уверены?' }  do %>
          <%= material_icon.delete.md_36 %>
        <% end %>
      </li>
    </ul>
<% end %>   
</div>
<div class="event-card row">
  <div class="card event-img col-md-6">
    <%= image_tag @event.event_image.url(:medium) %>
  </div>
  <div class="card event-info col-md-6">
    <div class="block-info event-date">  
    <%= material_icon.date_range.md_36 %><span><%= l(@event.date, format: '%d %A %Y, %-H:%M') %></span>
    </div>
    <div class="block-info event-address">
    <%= material_icon.place.md_36 %><span><%= @event.city %>, <%= @event.address %></span>
    </div>
    <div class="block-info event-link"> 
    <%= material_icon.link.md_36 %><span><%= link_to @event.link, @event.link, target: '_blank' %></span>
    </div>
    <div class="block-info event-organizer">
      <%= material_icon.face.md_36 %>
      <span>
      <%=
       link_to_if(@event.organizer.blank?, '') do
            link_to @event.organizer.name, @event.organizer
         end
       %>
       </span>
    </div>
    <div class="block-info button-group ml-auto form-row">
      <%= form_tag(subscribe_event_url, method: :post, class: 'form-inline') do %>
        <%= label_tag("Напомнить мне") %>
        <%= text_field_tag :email, nil, placeholder: 'email' %>
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
          <%= material_icon.done %>
        <% end %>
      <% end %>
      <%= button_to 'Скачать ICS', ics_event_url, method: :get, class: 'btn btn-success form-inline'%>
    </div>
  </div>
</div>
<div class="card event-desc d-flex col-md-10 justify-content-center">
<h1>Описание мероприятия</h1>
  <%= @event.description %>
</div>  

app/views/layouts/_footer.html.erb
<footer class="footer">
  <ul class="nav bg-secondary">
      <li class="nav-item">
          <%= link_to "Мероприятия", events_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to "Организаторы", organizers_path, class: "nav-link" %>
      </li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-primary top">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= material_icon.event.md_36%>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
         <div class="collapse navbar-collapse" id="navbarTop">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Мероприятия", events_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Организаторы", organizers_path, class: "nav-link" %>
                </li>
            </ul>
            <% if logged_in? %>
            <ul class="navbar-nav navbar-greeting ml-auto">
                <span class="greeting">Привет, Админ!</span>
                <li class="nav-item">
                    <%= link_to "Выйти", logout_path, method: :delete, class: "btn btn-info" %>
                </li>
            </ul>
            <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarBottom" aria-controls="navbarBottom" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        </div>
    </nav>
    <nav class="navbar navbar-expand-sm navbar-primary bg-light bottom">
         <div class="collapse navbar-collapse navbarBottom">
            <ul class="navbar-nav container">
                <li class="nav-item">
                <%= form_tag(filter_events_url, method: :get, class:'form-inline') do %>
                    <%= select_tag(:par, options_for_select(['Предстоящие','Прошедшие'].zip(['>','<'])), prompt: 'Когда', class: 'form-control')  %>
                    <%= collection_select nil, :city, Event.pluck(:city).uniq.sort, :to_s, :to_s, {prompt: 'Город'}, {class: 'form-control'} %>
                    <%# collection_select nil, :month, I18n.t('date.month_names').drop(1).zip(1..12), :to_s, :to_s, prompt: 'Месяц', class: 'form-control' %>
                    <%= select_tag(:month, options_for_select(I18n.t('date.month_names').drop(1).zip(1..12)), prompt: 'Месяц', class: 'form-control')  %>
                    <%= collection_select nil, :organizer_id, Organizer.all, :id, :name, {prompt: 'Организатор'}, {class: 'form-control'} %>
                    <%= button_tag(type: "submit", class: "btn btn-primary") do %>Найти<% end %>
                <% end  %>
                </li>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container container-content">  
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/organizers/_form.html.erb
<%= form_for @organizer, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages', object: @organizer %>

  <%= f.label 'Имя' %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label 'Описание' %>
  <%= f.text_area :description, class: 'form-control' %>

  <%# f.label :events %>
  <%# f.collection_select :events, Event.all, :id, :name %>

  <!-- <%= f.file_field :image %> !-->
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

app/views/organizers/_organizer.html.erb
<div class="col-md-6">
    <div class="card h-100">
        <div class="row no-gutters">
            <div class="col">
                <h5 class="card-title"><%= link_to organizer.name, organizer %></h5>
                <p class="card-text">
                </p>
            </div>
        </div>
    </div>
</div>

app/views/organizers/edit.html.erb
<% provide(:title, 'Изменить организатор') %>
<% provide(:button_text, 'Сохранить изменения') %>
<h1>Изменить организатора</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/organizers/index.html.erb
<% provide(:title, '') %>
<div class="row navbar-admin">
  <h1>Организаторы</h1>
  <% if logged_in? %>
    <span class="ml-auto">
      <%= link_to '/organizers/new', title: 'Добавить мероприятие' do %>
        <%= material_icon.add.md_36 %>
      <% end %>
    </span>
  <% end %>  
</div>
<div class="container-fluid orgs-container">
  <div class="row org-cards">
    <% @organizers.each do |organizer| %>
      <%= render organizer %>
    <% end %>
  </div>
</div>
<%= will_paginate @organizers, list_classes: %w(pagination justify-content-center) %>

app/views/organizers/new.html.erb
<% provide(:title, 'Новый организатор') %>
<% provide(:button_text, 'Создать') %>
<h1>Новый организатор</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/organizers/show.html.erb
<% provide(:title, @organizer.name) %>
<div class="container">  
  <div class="row">
    <h1 class="organizer-name"><%= @organizer.name %></h1>
    <% if logged_in? %>
      <ul class="navbar-nav navbar-admin ml-auto">
          <li class="nav-item">
            <%= link_to edit_organizer_path, title: 'Изменить организатора' do %>
              <%= material_icon.mode_edit.md_36 %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to @organizer, method: :delete, title: 'Удалить организатора', data: { confirm: 'Вы уверены?' }  do %>
              <%= material_icon.delete.md_36 %>
            <% end %>
          </li>
      </ul>
    <% end %> 
  </div>
  <div class="card event-desc col-md-12">
    <h2 class="card-title">Об организаторе</h2>
    <div class="card-body">
      <%= @organizer.description %>
    </div>
  </div>  
  <div class="card-group event-card row">
    <div class="card event-info col-md-12">
      <h2>Организованные мероприятия: </h2>
      <div class="row">
      <% @organizer.events.each do |event| %>
        <%= link_to event, class: 'col-md-6 border' do %>
          <%= event.name %>,
          <%= l(event.date, format: '%d %B %Y, %-H:%M') %>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if error_msg(controller).errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(error_msg(controller).errors.count, "error") %>.
    </div>
    <ul>
    <% error_msg(controller).errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>